name: ui
description: Find Up! multi-language package
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo


environment:
  sdk: '>=3.0.5 <4.0.0'

# Add regular dependencies here.
dependencies:
  dynamic_parallel_queue: ^1.0.3+2
  args: ^2.4.2
  csv: ^6.0.0
  vdf: ^1.1.0
  crypto: ^3.0.3
  get: ^4.6.6
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
